### ISSUE TITLE
Duplicate commands

### ISSUE THREAD

**Issue by caciobanu** [doesntmattr/mongodb-migrations-bundle#1]
Taking a look into https://github.com/doesntmattr/mongodb-migrations-bundle/tree/master/Command you can see that the content of commands with and without **Doctrine** in naming is the same, ex:
- https://github.com/doesntmattr/mongodb-migrations-bundle/blob/master/Command/MigrationsExecuteCommand.php
- https://github.com/doesntmattr/mongodb-migrations-bundle/blob/master/Command/MigrationsExecuteDoctrineCommand.php

Also in commit https://github.com/doesntmattr/mongodb-migrations-bundle/commit/c6d3bd3b08fdfffff602566a578b143684d25459 the message is **Rename commands**.

I think that we should check if we can deprecate the commands with **Doctrine** in naming and make them extend the ones without and in 2.0 release to delete them.

What do you guys say ?

**Comment by redthor** [comment]
I totally agree. Good idea. I hadn't noticed those duplicate classes.

Are you thinking of:
* adding a deprecated doc comment; and
* adding a deprecated php notice?

If we add the php notice it will probably show every time the container is compiled (when `-v`) is on.

The notice could say that the class is being removed but it will only affect anyone who has `use`d the class. No feature is being removed.

**Comment by caciobanu** [comment]
Yes, I was thinking of a deprecated doc comment and a PHP deprecated notice (E_USER_DEPRECATED). The former is useful when using the symfony/phpunit-bride package.

After we agree on how to proceed I'll try to get a PR ready.

**Comment by redthor** [comment]
I've create `2.0.0-dev` branch so we can get our PRs targeting that release.

**Comment by caciobanu** [comment]
I added some new questions on PR #3. It is important to get that sorted.

**Comment by caciobanu** [comment]
Closing as it was solved in #12.
