### ISSUE TITLE
AntiMattrCommand is not a Command

### ISSUE THREAD

**Issue by redthor** [doesntmattr/mongodb-migrations-bundle#2]
Looking at #1 I just noticed that:
`Command/AntiMattrCommand`
is not really a `Command`.

It `extends ContainerAwareCommand` but does not appear to use anything in that class.

I suggest that:

* rename to `AntiMattrCommandHelper`
* remove the `extends ContainerAwareCommand`

We might be able to change it to a trait? (I haven't thought that through, and we'd need to change php minimum to 5.4)

Here is the class:
https://github.com/doesntmattr/mongodb-migrations-bundle/blob/master/Command/AntiMattrCommand.php#L24

**Comment by caciobanu** [comment]
At a first look that class is not extended at all, but I have to check to be sure. It is used directly in the other command classes: https://github.com/doesntmattr/mongodb-migrations-bundle/blob/master/Command/MigrationsExecuteCommand.php#L36
Making it a helper could be a good idea. I'll think about it.

For the PHP version I suggest keeping compatible with the lowest version required by the Symfony supported versions. For now Symfony 2.8 (LTS) requires PHP 5.3.9.

**Comment by redthor** [comment]
Ok, agreed. Leave out traits, but change it to be a helper. I'll look into it.

**Comment by redthor** [comment]
See #3
