### ISSUE TITLE
InvalidArgumentException with Symfony2.8 and doctrine ODM

### ISSUE THREAD

**Issue by manuelbcd** [doesntmattr/mongodb-migrations-bundle#5]
Hi. I have been trying to test this bundle but after installation it always shows the same on console commands.

php app/console mongodb:migrations:status

>   [Symfony\Component\DependencyInjection\Exception\InvalidArgumentExcep
  The parameter "mongo_db_migrations.database_name" must be defined.

I have tried also to inject directly a configuration yml.

php app/console mongodb:migrations:status --configuration=/var/www/html/app/config/migrations.yml -vvv

But same problem.

My configuration file is exactly like the example.  Am I doing something wrong or is the doc outdate?

Thanks in advance

**Comment by redthor** [comment]
The config is still the same.

What does:

`php app/console debug:container --parameter=mongo_db_migrations.database_name`

show?

**Comment by manuelbcd** [comment]
@redthor  it was my fault. I was putting the configuration into parameters.yml instead of configuration.yml
Thank you

**Comment by redthor** [comment]
I'm glad it is resolved :)
