### ISSUE TITLE
Migrations diff

### ISSUE THREAD

**Issue by redayoub** [doesntmattr/mongodb-migrations-bundle#7]
Hello,

Is there an equivalent command for generating diff migrations like this "doctrine:migrations:diff" when using orm?

Thanks.

**Comment by redthor** [comment]
Hi @redayoub ,

I'm sorry, there isn't something like that for the ODM.

There are a few differences with using document-oriented MongoDB. For example the {{collection}} does not need to exist before using it to make inserts. And you don't need to make any changes in MongoDB when adding a new property etc.

Also MongoDB doesn't hold a set schema for each {{collection}}, so it is difficult to say what has changed. Changing a property name looks the same as adding a new one. There are tools like https://github.com/variety/variety that help with this but they use the fact that they can get to real data and analyse the structure there (something you won't normally have in development).

Did you have a particular example you can share of what you would like to auto-generate?

Thanks,
Doug

**Comment by redthor** [comment]
Closing for now
